# ------------------------------------------------------------------------
# Copyright (c) 2020-2023 Riccardo De Martis. MIT License.
# All Trademarks referred to are the property of their respective owners.
# ------------------------------------------------------------------------

# This is the master workflow, taken by CI of GitHub.
# It (only) aims at properly organizing the sub-workflows.

name: CI

on:
  push:
    branches:
      - "master"

concurrency:
  group: CI-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DOCKERHUB_REPO: demartis/matlab-runtime

jobs:
  Prepare:
    uses: ./.github/workflows/sub_prepare.yaml

  Description:
    needs: [ Prepare ]
    uses: ./.github/workflows/sub_description.yaml
    secrets: inherit

  R2020a:
    needs: [ Prepare ]
    uses: ./.github/workflows/sub_release.yaml
    secrets: inherit
    with:
      DOCKERHUB_TAG: R2020a
      DOCKER_CONTEXT: R2020a
      is_latest: true
