# ------------------------------------------------------------------------
# Copyright (c) 2020-2023 Riccardo De Martis. MIT License.
# All Trademarks referred to are the property of their respective owners.
# ------------------------------------------------------------------------

# This is the master workflow, taken by CI of GitHub.
# It (only) aims at properly organizing the sub-workflows.

name: CI

on:
  push:
    branches:
      - "master"

concurrency:
  group: CI-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Description:
    uses: ./.github/workflows/sub_description.yaml
    with:
      DOCKERHUB_REPO: demartis/matlab-runtime
    secrets: inherit

  R2019b:
    uses: ./.github/workflows/sub_release.yaml
    with:
      DOCKERHUB_REPO: demartis/matlab-runtime
      DOCKERHUB_TAG: R2019b
      DOCKER_CONTEXT: R2019b
    secrets: inherit

  R2019b-meshlab:
    needs: [ R2019b ]
    uses: ./.github/workflows/sub_release.yaml
    with:
      DOCKERHUB_REPO: demartis/matlab-runtime
      DOCKERHUB_TAG: R2019b-meshlab
      DOCKER_CONTEXT: R2019b-meshlab
    secrets: inherit

  R2020a:
    uses: ./.github/workflows/sub_release.yaml
    with:
      DOCKERHUB_REPO: demartis/matlab-runtime
      DOCKERHUB_TAG: R2020a
      DOCKER_CONTEXT: R2020a
      is_latest: true
    secrets: inherit

  R2020a-meshlab:
    needs: [ R2020a ]
    uses: ./.github/workflows/sub_release.yaml
    with:
      DOCKERHUB_REPO: demartis/matlab-runtime
      DOCKERHUB_TAG: R2020a-meshlab
      DOCKER_CONTEXT: R2020a-meshlab
      is_latest_meshlab: true
    secrets: inherit
