# ------------------------------------------------------------------------
# Copyright (c) 2020-2023 Riccardo De Martis. MIT License.
# All Trademarks referred to are the property of their respective owners.
# ------------------------------------------------------------------------

name: Release

on:
  workflow_call:
    inputs:
      DOCKERHUB_TAG:
        required: true
        type: string
      DOCKER_CONTEXT:
        required: true
        type: string
      is_latest:
        required: false
        default: false
        type: bool


jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      -
        name: Build and export to Docker ${{ inputs.DOCKERHUB_TAG }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.DOCKER_CONTEXT }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ inputs.DOCKERHUB_TAG }}
            ${{ inputs.is_latest && env.DOCKERHUB_REPO':latest' || '' }}
          #          outputs: type=docker,dest=/tmp/myimage.tar
      -
        name: Inspect
        run: |
          docker image inspect ${{ env.DOCKERHUB_REPO }}:${{ inputs.DOCKERHUB_TAG }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.DOCKERHUB_REPO }}:${{ inputs.DOCKERHUB_TAG }} echo "TODO: ADD MCR TEST"

#      -
#        name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: myimage
#          path: /tmp/myimage.tar

#  use:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      -
#        name: Download artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: myimage
#          path: /tmp
#      -
#        name: Load image
#        run: |
#          docker load --input /tmp/myimage.tar
#          docker image ls -a