name: R2020a

env:
  LATEST_TAG: latest


jobs:

  
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: ./latest
          tags: ${{ env.REPO }}:${{ env.LATEST_TAG }}
          #          outputs: type=docker,dest=/tmp/myimage.tar
      -
        name: Inspect
        run: |
          docker image inspect ${{ env.REPO }}:${{ env.LATEST_TAG }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.REPO }}:${{ env.LATEST_TAG }} echo "TODO: ADD MCR TEST"

      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.REPO }}

#      -
#        name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: myimage
#          path: /tmp/myimage.tar

#  use:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      -
#        name: Download artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: myimage
#          path: /tmp
#      -
#        name: Load image
#        run: |
#          docker load --input /tmp/myimage.tar
#          docker image ls -a